// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MindChess",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MindChess",
            targets: ["AppModule"],
            bundleIdentifier: "com.CharlesProduct.MindChess",
            teamIdentifier: "6AC96KL793",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .speechRecognition(purposeString: "Voice recognition will allow you to move the chess pieces using your voice."),
                .microphone(purposeString: "The microphone is used for voice recognition")
            ],
            appCategory: .boardGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)